### ISSUE TITLE
Cannot find module '@nrwl/workspace/tasks-runners/default'

### ISSUE THREAD

**Issue by NullVoxPopuli** [robinpellegrims/pellegrims#156]
**Describe the bug**
Looks to be the same as: https://github.com/bojanbass/nx-aws/issues/126

**To Reproduce**

1. Have only `nx` installed
2. install "@pellegrims/nx-remotecache-s3": "^1.2.1",`
3. make the updates to the nx.json specified in the readme
4. use nx
5. error

**Expected behavior**

no error

**Additional context**

It's fine if this is a required package, but a `peerDependencies` entry would be a good way to communicate that need.
Or, if because I'm using nx 14 with no plugins, and the default task runner (in nx.json) is: "runner": "nx/tasks-runners/default",
should I even need `@nrwl/workspace` at all?

**Comment by robinpellegrims** [comment]
I think you're right, this package depends on [nx-remotecache-custom](https://github.com/NiklasPor/nx-remotecache-custom), which in turn has a peer dependency on `@nrwl/workspace` (because that's where the RemoteCache stuff lives), so I guess we need to forward this peer dependency in this package as well.

**Comment by robinpellegrims** [comment]
Should be fixed in v1.2.2. Thanks for reporting!
