### ISSUE TITLE
NX_S3 specific environment AWS keys

### ISSUE THREAD

**Issue by juddgaddie** [robinpellegrims/pellegrims#169]
We want to be able to specify keys via environment variables that are lower priority in the key provider resolution chain to AWS_ACCESS_KEY_ID ie. not override a users credentials in ~/.aws/credentials

Since [@aws-sdk/credential-provider-node](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html) in version 1.0.0 
NX_CACHE_S3_ACCESS_KEY_ID
NX_CACHE_S3_SECRET_KEY 

was removed

**Describe the solution you'd like**
NX_CACHE_S3_ACCESS_KEY_ID -> then continue with default provider chain.
We could add a provider which checks for NX_ earlier in the provider chain.

**Describe alternatives you've considered**
Seeing if this can be done in some way directly with https://www.npmjs.com/package/%40aws-sdk/credential-provider-node - coulldn't find a clean way through it, open to ideas.

**Comment by robinpellegrims** [comment]
If I understand correctly, you want a workaround for the following logic in [@aws-sdk/credential-provider-node](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html#aws-sdkcredential-provider-node):
`if the process finds values defined via the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables, the files at ~/.aws/credentials and ~/.aws/config will not be read, nor will any messages be sent to the Instance Metadata Service.`

So providing our own custom environment variables for the key/secret would enrich the information in ~/.aws/credentials and not ignore it like AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY?

I'm a bit hesitant about this, as it might cause mistakes because of confusion between the AWS and our own environment variables for key/secret. A solution would be to choose clear env variable names that indicate this will continue with the default provider chain.

For my information, could you elaborate a little more on why you need this, do you have a specific use case in mind?

**Comment by juddgaddie** [comment]
Sorry only saw this message now, thanks for the reply.

The specific issue is:
We have a specific key which only provides access to NX Cache in our S3 respository, this is a shared key.
We want @pellegrims/nx-remotecache-s3 to use this key by default, i.e. by reading NX_CACHE_S3_ACCESS_KEY_ID, NX_CACHE_S3_SECRET_KEY

If the NX_CACHE_S3_ACCESS_KEY_ID, NX_CACHE_S3_SECRET_KEY is not found then just use the normal aws credential resolution. You could call this DEFAULT_NX_CACHE_S3_ACCESS_KEY

I think the way AWS way to solve this is with [profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html), however I don't beleive you can specify a profile KEY_ID and SECREY_KEY via an environment variable only in the .aws/credentials file so it doesn't help.

We use this same approach from another s3 build cache tool from the Java ecosystem e.g. https://github.com/burrunan/gradle-s3-build-cache.

**Comment by robinpellegrims** [comment]
Sure ok, would you like to provide a PR?

**Comment by robinpellegrims** [comment]
fixed in #199 
released in v2.1.0
