### ISSUE TITLE
Generated package.json is pinning all dependency versions

### ISSUE THREAD

**Issue by kellyselden** [robinpellegrims/pellegrims#181]
I'm curious why the latest release switched to pinning everything? https://app.renovatebot.com/package-diff?name=@pellegrims%2fnx-remotecache-s3&from=1.4.3&to=1.4.4. Was this an accident? This caused some of our nested deps to have to get downgraded. Floating should be the better choice for libraries, and allow the lockfile of consumers to do the pinning. Then we can update the nested deps ourselves all we want without waiting for a release for this library.

**Comment by robinpellegrims** [comment]
I agree, thanks for reporting this. 

This is a regression caused by the upgrade of nx to v15. The package.json for the library to be published is [generated by nx](https://nx.dev/more-concepts/buildable-and-publishable-libraries#publishable-libraries) and according to [this issue](https://github.com/nrwl/nx/issues/12675), it seems they [intentionally](https://github.com/nrwl/nx/issues/12675#issuecomment-1297000614) modified the way the versions are calculated.

I will manually define the ranged versions in the package.json file for nx-remotecache-s3.

**Comment by josephdpurcell** [comment]
I've been scouring for solutions to this very issue with NX, and I very much appreciate that you documented the solution.

The NX tickets are closed, so just in case someone runs across this I'll share what I did. Now that `targetDefaults` are a thing (see PR https://github.com/nrwl/nx/pull/12435), I was able to put this in my root `nx.json` file:

```json
  "targetDefaults": {
    "build": {
      "options": {
        "updateBuildableProjectDepsInPackageJson": false
      }
```

And this disables the automagic additions of dependencies which since moving to NX 15 has been unpredictable and painful, so I'm switching to manual unless/until there's a way to do pre-15 style management. I submitted a stackoverflow on it: https://stackoverflow.com/q/76097683/990642.
