### ISSUE TITLE
Release nx-remotecache-s3@2.0.1

### ISSUE THREAD

**Issue by Charlie-Crowdstrike** [robinpellegrims/pellegrims#195]
**Is your feature request related to a problem? Please describe.**

We currently consume `nx-remotecache-s3@2.0.0` in our project, which hard-pins many `@aws-sdk` packages, including ones that contains a [vulnerability in fast-xml-parser](https://ossindex.sonatype.org/vulnerability/sonatype-2023-0998?component-type=npm&component-name=fast-xml-parser&utm_source=auditjs&utm_medium=integration&utm_content=4.0.39) . I see that `nx-remotecache-s3@2.0.1` fixes this, and the last commit message says `release 2.0.1`, but the latest version on `npm` is `2.0.0`

Was that commit message accurate? Or are there blockers to releasing `2.0.1`?

**Describe the solution you'd like**
Release `2.0.1`

**Additional context**
Bonus question, are there any plans to move forward off of `nx-remotecache-s3@1.4.7` in the root project?

**Comment by robinpellegrims** [comment]
Thanks for reporting this. There seems to be an issue preventing us to deploy to npm because of an [incompatibility issue](https://github.com/bikecoders/ngx-deploy-npm/issues/471) between nx v15.6.3 (current version of nx in this repository) and ngx-deploy-npm.

I'll try to upgrade ngx-deploy-npm to v5 to see if that solves the issue.

**Comment by Charlie-Crowdstrike** [comment]
Thank you!

**Comment by robinpellegrims** [comment]
> **Additional context** Bonus question, are there any plans to move forward off of `nx-remotecache-s3@1.4.7` in the root project?

Yes, this is being taken care of in #203
