### ISSUE TITLE
Generated package.json is pinning all dependency versions

### ISSUE THREAD

**Issue by kellyselden** [robinpellegrims/pellegrims#198]
It looks like https://github.com/robinpellegrims/pellegrims/issues/181 has regressed https://app.renovatebot.com/package-diff?name=@pellegrims%2fnx-remotecache-s3&from=2.0.0&to=2.0.1.

**Comment by Charlie-Crowdstrike** [comment]
To add to this, there is a vulnerability within the pinned `@aws-sdk/*` packages `@3.231.0` in `nx-remotecache-s3@2.0.1`, more details here: https://github.com/robinpellegrims/pellegrims/issues/195

**Comment by robinpellegrims** [comment]
seems like updating nx again changed the behavior
adding `"updateBuildableProjectDepsInPackageJson": false` seems to fix it

**Comment by robinpellegrims** [comment]
Fixed in [v2.0.2](https://www.npmjs.com/package/@pellegrims/nx-remotecache-s3/v/2.0.2). I noticed afterwards that @aws-sdk/client-s3 was missing from the built package.json, so I explicitly added it again in [v2.0.3](https://www.npmjs.com/package/@pellegrims/nx-remotecache-s3/v/2.0.3).

> To add to this, there is a vulnerability within the pinned `@aws-sdk/*` packages `@3.231.0` in `nx-remotecache-s3@2.0.1`, more details here: #195

Created a separate issue based on this comment: #200

**Comment by Charlie-Crowdstrike** [comment]
Thank you! Quick response :)
